// <auto-generated />
using System;
using MegaCentralFinanceBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MegaCentralFinanceBackend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241102013631_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MegaCentralFinanceBackend.Models.ms_storage_location", b =>
                {
                    b.Property<string>("location_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("location_id");

                    b.ToTable("storageLocations");
                });

            modelBuilder.Entity("MegaCentralFinanceBackend.Models.ms_user", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"), 1L, 1);

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MegaCentralFinanceBackend.Models.tr_bpkb", b =>
                {
                    b.Property<string>("agreement_number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("bpkb_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bpkb_date_in")
                        .HasColumnType("datetime2");

                    b.Property<string>("bpkb_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("faktur_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("faktur_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_updated_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_updated_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("location_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("police_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("agreement_number");

                    b.ToTable("TransactionBPKB");
                });
#pragma warning restore 612, 618
        }
    }
}
